name: Pypi
on:
  push:
    paths-ignore:
      - '*.md'
      - 'LICENSE'

jobs:
  Publish:
    name: Publish
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Python Models
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install wheel
      - name: Build Python package
        run: |
          sed -i "s/__version__ = \".*/__version__ = \"$(git describe --tags |  sed  's/\([^-]*-g\)/r\1/;s/-/./g')\"/g" dfm/_version.py
          python3 ./setup.py sdist bdist_wheel
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
